name: Pytest action

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
    test:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.9.14"]
      name: Run tests
      steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Run Pytest
        working-directory: src/
        run: python -m pytest

